version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/wh0isdxk/chevron"
  dependencies_vendored = true

[[analyzers]]
name = "test-coverage"
enabled = true