name: Securego 
# This workflow verificate all security issues in the code.
on: [push]

jobs:
 security:
    name: Review security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check missing error check
      uses: "cedrickring/golang-action@1.3.0"
      with:
args: go get github.com/securego/gosec/sh/gosec
