name: Go
on: [push]

jobs:
  security:
    name: Review security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check missing error check
      uses: "securego/gosec@v2.1.0"
      with:
        args: ./...
