name: Securego 
# This workflow verificate all security issues in the code.
on: [push]

jobs:
  build:
    name: Golangsec
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's secure go https://github.com/securego/gosec
      - name: Gosec
        uses: actions/securego/gosec:v2.1.0
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Results
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
