name: Go
on:
  pull_request:
    branches:
    - feature/*
  push:
    branches:
    - feature/*
jobs:
  security:
    name: Review security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check missing error check
      uses: "securego/gosec@v2.1.0"
      with:
args: go get github.com/securego/gosec/sh/gosec; gosec ./... # https://github.com/securego/gosec 
